app:
  server: 8000
  endpoint:
    GET:
      type:
        json:
          response:
            sistemas: pamonha
    POST:
      type:
        json:
          request:
            sistemas: pirulito
  core:
    arrays:
      type1: [item1, item2, item3, item4]
      type2:
        - item1
        - item2

app:
  server: 8080
  endpoint: a